//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidUpdate1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel
    {
        public int Id { get; set; }
        public string Location { get; set; }
        public string Data { get; set; }
    }
}
